const s={i:0,who:'',goal:'',cal:'',meal:'',table:'',location:'',pay:'card'};
const screens=[...document.querySelectorAll('.screen')],title=document.querySelector('#title'),sub=document.querySelector('#subtitle');
const titles=['Xush kelibsiz!','Kim uchun?','Maqsadingiz nima?','Kunlik kaloriya','Ovqatlanish turi','Yetkazib berish','Buyurtmangiz'];
const subs=['Siz uchun qulay va foydali ovqatlanish rejasini tanlang.','Buyurtma kim uchun ekanini belgilang.','Maqsadingizga mos menyuni tanlang.','Sizga mos kunlik kaloriyani tanlang.','Ovqatlanish rejangizni belgilang.','Stol va yetkazib berish ma’lumotlarini kiriting.','Ma’lumotlarni tekshiring va to‘lovni tanlang.'];
function render(){screens.forEach((x,i)=>x.classList.toggle('active',i===s.i));title.textContent=titles[s.i];sub.textContent=subs[s.i];document.querySelector('#step').textContent=(s.i+1)+' / 7';document.querySelector('#back').classList.toggle('hidden',s.i===0);document.querySelector('#next').textContent=s.i===6?'Buyurtma berish':'Davom etish';if(s.i===6)summary()}
function pick(selector,key,value){document.querySelectorAll(selector).forEach(x=>x.classList.toggle('selected',x.dataset[key]===value))}
document.querySelectorAll('[data-who]').forEach(x=>x.onclick=()=>{s.who=x.dataset.who;pick('[data-who]','who',s.who);document.querySelector('#recipient').classList.toggle('hidden',s.who!=='other')});
document.querySelectorAll('[data-goal]').forEach(x=>x.onclick=()=>{s.goal=x.dataset.goal;pick('[data-goal]','goal',s.goal)});
document.querySelectorAll('[data-cal]').forEach(x=>x.onclick=()=>{s.cal=x.dataset.cal;pick('[data-cal]','cal',s.cal)});
document.querySelectorAll('[data-meal]').forEach(x=>x.onclick=()=>{s.meal=x.dataset.meal;pick('[data-meal]','meal',s.meal)});
document.querySelectorAll('[data-pay]').forEach(x=>x.onclick=()=>{s.pay=x.dataset.pay;document.querySelectorAll('[data-pay]').forEach(y=>y.classList.toggle('selected',y===x))});
document.querySelector('#loc').onclick=()=>{const p=document.querySelector('#locStatus');if(!navigator.geolocation){p.textContent='Geolokatsiya mavjud emas.';return}p.textContent='Aniqlanmoqda...';navigator.geolocation.getCurrentPosition(x=>{s.location=x.coords.latitude.toFixed(5)+', '+x.coords.longitude.toFixed(5);p.textContent='✓ Joylashuv aniqlandi'},()=>p.textContent='Joylashuvga ruxsat berilmadi.')};
function validate(){if(s.i===0){if(!document.querySelector('#name').value.trim()||!document.querySelector('#surname').value.trim()||!document.querySelector('#phone').value.trim())return'Ism, familiya va telefonni kiriting.'}if(s.i===1&&!s.who)return'Kim uchun buyurtma ekanini tanlang.';if(s.i===2&&!s.goal)return'Maqsadni tanlang.';if(s.i===3&&!s.cal)return'Kaloriyani tanlang.';if(s.i===4&&!s.meal)return'Ovqatlanish turini tanlang.';if(s.i===5){s.table=document.querySelector('#table').value.trim();if(!s.table)return'Stol raqamini kiriting.'}return''}
function summary(){const g={loss:'Vazn tashlash',form:'Formani saqlash',gain:'Vazn yig‘ish'};document.querySelector('#summary').innerHTML=[['Mijoz',document.querySelector('#name').value+' '+document.querySelector('#surname').value],['Telefon',document.querySelector('#phone').value],['Kim uchun',s.who==='other'?'Boshqaga':'O‘zimga'],['Maqsad',g[s.goal]],['Kaloriya',s.cal==='individual'?'Individual':s.cal+' kcal'],['Menyu',s.meal==='individual'?'Individual':'Standart'],['Stol',s.table]].map(x=>'<div class="sum"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')}
document.querySelector('#flow').onsubmit=e=>{e.preventDefault();const err=validate();if(err){alert(err);return}if(s.i<6){s.i++;render()}else{document.querySelector('#flow').classList.add('hidden');document.querySelector('.hero').classList.add('hidden');document.querySelector('#success').classList.remove('hidden')}};
document.querySelector('#back').onclick=()=>{if(s.i){s.i--;render()}};render();