const images=['assets/meal-0.webp','assets/meal-1.webp','assets/meal-2.webp','assets/meal-3.webp'];
const meals=[{id:0,name:'Tovuq va kinoa',price:59000,kcal:520,protein:38,fat:18,carb:49,cat:'protein',desc:'Grilda pishirilgan tovuq filesi, kinoa, avokado, brokkoli va cherri pomidorlari.',allergen:'Individual allergiyalarni buyurtmadan oldin tekshiring.'},{id:1,name:'Losos va ko‘katlar',price:79000,kcal:460,protein:34,fat:28,carb:18,cat:'protein',desc:'Grilda pishirilgan losos, yangi ko‘katlar, bodring va limon. Yengil, to‘yimli tushlik.',allergen:'Baliq mavjud.'},{id:2,name:'Vegan sabzavotli kosa',price:49000,kcal:410,protein:16,fat:14,carb:55,cat:'vegan',desc:'No‘xat, xummus, qizil karam, ko‘katlar va pomidor. O‘simlik mahsulotlaridan tayyorlangan.',allergen:'Xummus tarkibida kunjut bo‘lishi mumkin.'},{id:3,name:'Mevali suli bo‘tqasi',price:29000,kcal:350,protein:12,fat:11,carb:52,cat:'breakfast',desc:'Suli bo‘tqasi, qulupnay, chernika va bodom. Kunni mazali boshlash uchun.',allergen:'Bodom mavjud. Suli tarkibida gluten izlari bo‘lishi mumkin.'}];
const $=id=>document.getElementById(id),money=n=>n.toLocaleString('ru-RU')+' so‘m';let cart={},saved=new Set(),category='all',view='menu',lowCal=false,previousFocus=null,toastTimer;
const icons={plus:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>',heart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/></svg>',close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>',minus:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14"/></svg>'};
function toast(t){clearTimeout(toastTimer);$('toast').textContent=t;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,1800)}
function render(){let term=$('search').value.toLocaleLowerCase().replace(/[‘’']/g,'');let result=meals.filter(m=>(category==='all'||m.cat===category)&&(!lowCal||m.kcal<=450)&&(view!=='saved'||saved.has(m.id))&&m.name.toLocaleLowerCase().replace(/[‘’']/g,'').includes(term));$('sectionTitle').textContent=view==='saved'?'Sevimli taomlar':'Bugungi menyu';$('hero').hidden=view==='saved';$('grid').innerHTML=result.length?result.map(m=>`<article class="meal"><div class="picture"><button onclick="detail(${m.id})" aria-label="${m.name} haqida"><img src="${images[m.id]}" alt="${m.name}"></button><button class="fav ${saved.has(m.id)?'on':''}" onclick="favorite(${m.id})" aria-label="${m.name}: sevimlilarga ${saved.has(m.id)?'olib tashlash':'qo‘shish'}" aria-pressed="${saved.has(m.id)}">${icons.heart}</button></div><div class="mealBody"><button class="mealTitle" onclick="detail(${m.id})"><h3>${m.name}</h3></button><div class="nutrition"><span class="kcal">${m.kcal} kkal</span><span>· ${m.protein} g oqsil</span></div><div class="priceRow"><div class="price">${money(m.price).replace(' so‘m','')}<small>so‘m / porsiya</small></div><button class="add" onclick="add(${m.id})" aria-label="${m.name}: savatga qo‘shish">${icons.plus}</button></div></div></article>`).join(''):`<div class="empty">${icons.heart}<h3>${view==='saved'?'Hali sevimli taom yo‘q':'Taom topilmadi'}</h3><p>${view==='saved'?'Yoqtirgan taomingizdagi yurakchani bosing.':'Boshqa so‘z bilan qidiring yoki filtrlarni tozalang.'}</p><button class="secondary" onclick="resetMenu()">Menyuga qaytish</button></div>`}
function resetMenu(){category='all';lowCal=false;$('search').value='';setView('menu');updateChips()}
function updateChips(){document.querySelectorAll('[data-cat]').forEach(b=>{b.classList.toggle('active',b.dataset.cat===category);b.setAttribute('aria-pressed',b.dataset.cat===category)});$('filterBtn').style.background=lowCal?'#d2e4f5':''}
function favorite(id){saved.has(id)?saved.delete(id):saved.add(id);render()}
function add(id){cart[id]=(cart[id]||0)+1;updateCart();toast('Taom savatga qo‘shildi')}
function total(){return Object.entries(cart).reduce((a,[id,n])=>a+meals[id].price*n,0)}
function count(){return Object.values(cart).reduce((a,n)=>a+n,0)}
function updateCart(){$('cartCount').hidden=!count();$('cartCount').textContent=count();$('cartbar').hidden=!count();$('cartbarCount').textContent=`Savat · ${count()} ta taom`;$('cartbarTotal').textContent=money(total())}
function setView(v){view=v;document.querySelectorAll('[data-nav]').forEach(b=>{let active=b.dataset.nav===v;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});render()}
function openDialog(title,body){previousFocus=document.activeElement;$('sheet').innerHTML=`<div class="sheetHead"><h2 id="dialogTitle">${title}</h2><button class="close" id="closeDialog" aria-label="Yopish">${icons.close}</button></div>${body}`;$('overlay').hidden=false;$('closeDialog').onclick=closeDialog;[...$('app').children].filter(c=>c.id!=='overlay'&&c.id!=='toast').forEach(c=>c.inert=true);$('closeDialog').focus()}
function closeDialog(){$('overlay').hidden=true;[...$('app').children].forEach(c=>c.inert=false);if(previousFocus?.isConnected)previousFocus.focus()}
function detail(id){let m=meals[id];openDialog(m.name,`<img class="detailImg" src="${images[id]}" alt="${m.name}"><p>${m.desc}</p><div class="macros"><div class="macro"><strong>${m.kcal}</strong><span>kkal</span></div><div class="macro"><strong>${m.protein} g</strong><span>Oqsil</span></div><div class="macro"><strong>${m.fat} g</strong><span>Yog‘</span></div><div class="macro"><strong>${m.carb} g</strong><span>Uglevod</span></div></div><div class="allergen"><strong>Allergenlar:</strong> ${m.allergen}</div><button class="primary" onclick="add(${id});closeDialog()">Savatga qo‘shish · ${money(m.price)}</button>`)}
function cartView(){if(!count()){openDialog('Savatingiz',`<div class="empty"><h3>Savat hozircha bo‘sh</h3><p>Menyudan sizga yoqqan taomni tanlang.</p><button class="primary" onclick="closeDialog();resetMenu()">Taom tanlash</button></div>`);return}openDialog('Savatingiz',Object.entries(cart).map(([id,n])=>`<div class="cartItem"><img src="${images[id]}" alt="${meals[id].name}"><div class="cartInfo"><h3>${meals[id].name}</h3><div class="small">${money(meals[id].price)}</div><div class="stepper"><button onclick="change(${id},-1)" aria-label="${meals[id].name}: kamaytirish">${icons.minus}</button><span>${n}</span><button onclick="change(${id},1)" aria-label="${meals[id].name}: ko‘paytirish">${icons.plus}</button></div></div></div>`).join('')+`<div class="totals"><div class="row between"><span>Taomlar</span><span>${money(total())}</span></div><div class="row between"><span>Yetkazish</span><span>${money(10000)}</span></div><div class="row between total"><span>Jami</span><span>${money(total()+10000)}</span></div></div><button class="primary" onclick="checkout()">Rasmiylashtirish</button><p>Demo savat — haqiqiy buyurtma yuborilmaydi.</p>`)}
function change(id,d){cart[id]+=d;if(cart[id]<=0)delete cart[id];updateCart();cartView()}
function checkout(){openDialog('Buyurtmani tekshirish',`<div class="notice">Bu interfeys prototipi. To‘lov olinmaydi va kuryer chaqirilmaydi.</div><form id="checkoutForm"><label class="field"><span>Telefon raqamingiz</span><input type="tel" placeholder="+998 90 123 45 67" required pattern="[+0-9 ()-]{9,20}"></label><label class="field"><span>Yetkazish manzili</span><input id="checkoutAddress" required></label><label class="field"><span>Yetkazish vaqti</span><select><option>Imkon qadar tez — 30–40 daqiqa</option><option>Bugun, 12:00–13:00</option><option>Bugun, 18:00–19:00</option></select></label><div class="totals"><div class="row between total"><span>Jami</span><span>${money(total()+10000)}</span></div></div><button type="submit" class="primary">Demo buyurtmani tasdiqlash</button></form>`);$('checkoutAddress').value=$('addressText').textContent;$('checkoutForm').onsubmit=e=>{e.preventDefault();cart={};updateCart();openDialog('Demo tayyor!',`<div class="empty"><h3>Buyurtma oqimi yakunlandi</h3><p>Haqiqiy buyurtma yuborilmadi. Jonli servis uchun to‘lov va buyurtma tizimi ulanishi kerak.</p><button class="primary" onclick="closeDialog();resetMenu()">Menyuga qaytish</button></div>`)}}
$('search').oninput=render;$('heroBtn').onclick=()=>detail(0);$('cartbar').onclick=cartView;
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;updateChips();render()});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>b.dataset.nav==='cart'?cartView():setView(b.dataset.nav));
$('addressBtn').onclick=()=>{openDialog('Yetkazish manzili',`<form id="addressForm"><label class="field"><span>Shahar, tuman va ko‘cha</span><input id="addressInput" required maxlength="90"></label><button type="submit" class="primary">Manzilni saqlash</button></form><p>Manzil faqat ushbu demo sessiyasida saqlanadi.</p>`);$('addressInput').value=$('addressText').textContent;$('addressForm').onsubmit=e=>{e.preventDefault();let v=$('addressInput').value.trim();if(!v)return;$('addressText').textContent=v;closeDialog();toast('Manzil yangilandi')}};
$('filterBtn').onclick=()=>{openDialog('Sizga mos taomlar',`<p>Oziqaviy qiymat bo‘yicha tanlang.</p><label class="check"><input type="checkbox" id="lowCal" ${lowCal?'checked':''}>450 kkalgacha bo‘lgan taomlar</label><p>Ma’lumotlar namunaviy. Bu tibbiy tavsiya emas.</p><button class="primary" id="applyFilter">Filtrni qo‘llash</button><button class="secondary" id="clearFilter" style="width:100%;margin-top:12px">Filtrlarni tozalash</button>`);$('applyFilter').onclick=()=>{lowCal=$('lowCal').checked;updateChips();render();closeDialog()};$('clearFilter').onclick=()=>{lowCal=false;category='all';updateChips();render();closeDialog()}};
$('profileBtn').onclick=()=>openDialog('Profil',`<div class="profile"><strong>Salom!</strong><p>Sog‘lom tanlov shu yerdan boshlanadi.</p></div><div class="notice">Demo profil. Telegram akkaunti va buyurtmalar tarixi hali ulanmagan.</div><button class="primary" onclick="closeDialog();document.getElementById('addressBtn').click()">Manzilni o‘zgartirish</button>`);
$('overlay').onclick=e=>{if(e.target===$('overlay'))closeDialog()};document.addEventListener('keydown',e=>{if($('overlay').hidden)return;if(e.key==='Escape'){closeDialog();return}if(e.key==='Tab'){let f=[...$('sheet').querySelectorAll('button,input,select,[tabindex]')].filter(el=>!el.disabled&&el.offsetParent!==null);let first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});render();